language:
  - generic

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gfortran-6
      env: CC='gcc-6' CXX='g++-6' FC='gfortran-6' COVERAGE='ON'

    - os: linux
      dist: trusty
      compiler: clang-3.6
      addons: &clang36
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty']
          packages:
            - clang-3.6
            - gfortran-6
      env: CC='clang-3.6' CXX='clang++-3.6' FC='gfortran-6'

    - os: linux
      dist: xenial
      compiler: clang-4.0
      before_install:
        - export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
      addons: &clang40
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages:
            - clang-4.0
            - gfortran-6
      env: CC='clang-4.0' CXX='clang++-4.0' FC='gfortran-6'

    - os: linux
      dist: trusty
      compiler: gcc-4.4
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-4.4
            - g++-4.4
            - gfortran-4.4
      env: CC='gcc-4.4' CXX='g++-4.4' FC='gfortran-4.4'

    - os: linux
      dist: trusty
      compiler: gcc-4.7
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-4.7
            - g++-4.7
            - gfortran-4.7
      env: CC='gcc-4.7' CXX='g++-4.7' FC='gfortran-4.7'

    - os: linux
      dist: trusty
      compiler: gcc-4.8
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - g++-4.8
            - gfortran-4.8
      env: CC='gcc-4.8' CXX='g++-4.8' FC='gfortran-4.8'

    - os: linux
      dist: trusty
      compiler: gcc-4.9
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
            - gfortran-4.9
      env: CC='gcc-4.9' CXX='g++-4.9' FC='gfortran-4.9'

    - os: linux
      dist: trusty
      compiler: gcc-5
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
            - gfortran-5
      env: CC='gcc-5' CXX='g++-5' FC='gfortran-5'

    - os: linux
      dist: trusty
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gfortran-6
      env: CC='gcc-6' CXX='g++-6' FC='gfortran-6' C_STANDARD='90'

    - os: linux
      dist: trusty
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gfortran-6
      env: CC='gcc-6' CXX='g++-6' FC='gfortran-6' C_STANDARD='11'

    - os: linux
      dist: trusty
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gfortran-6
      env: CC='gcc-6' CXX='g++-6' FC='gfortran-6' CXX_STANDARD='11'

    - os: linux
      dist: trusty
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gfortran-6
      env: CC='gcc-6' CXX='g++-6' FC='gfortran-6' CXX_STANDARD='14'

    - os: linux
      dist: trusty
      compiler: gcc-6
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gfortran-6
      env: CC='gcc-6' CXX='g++-6' FC='gfortran-6'

    - os: osx
      osx_image: xcode7.3
      compiler: gcc
      env: CC='gcc' CXX='g++' FC='gfortran'

    - os: osx
      osx_image: xcode8.3
      compiler: gcc
      env: CC='gcc' CXX='g++' FC='gfortran'

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: CC='clang' CXX='clang++' FC='gfortran'

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: CC='clang' CXX='clang++' FC='gfortran'

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - LLVM_INSTALL=${DEPS_DIR}/llvm/install
  - mkdir -p ${LLVM_INSTALL} && cd ${DEPS_DIR}
  - |
    # if in linux and compiler clang and llvm not installed
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${CXX%%+*}" == "clang" && -n "$(ls -A ${LLVM_INSTALL})" ]]; then
      if   [[ "${CXX}" == "clang++-3.6" ]]; then LLVM_VERSION="3.6.2";
      elif [[ "${CXX}" == "clang++-4.0" ]]; then LLVM_VERSION="4.0.0";
      fi
      LLVM_URL="http://llvm.org/releases/${LLVM_VERSION}/llvm-${LLVM_VERSION}.src.tar.xz"
      LIBCXX_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxx-${LLVM_VERSION}.src.tar.xz"
      LIBCXXABI_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxxabi-${LLVM_VERSION}.src.tar.xz"
      mkdir -p llvm llvm/build llvm/projects/libcxx llvm/projects/libcxxabi
      travis_retry wget -O - ${LLVM_URL} | tar --strip-components=1 -xJ -C llvm
      travis_retry wget -O - ${LIBCXX_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxx
      travis_retry wget -O - ${LIBCXXABI_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxxabi
      (cd llvm/build && cmake .. -DCMAKE_INSTALL_PREFIX=${LLVM_INSTALL})
      (cd llvm/build/projects/libcxx && make install -j2)
      (cd llvm/build/projects/libcxxabi && make install -j2)
      export CXXFLAGS="-isystem ${LLVM_INSTALL}/include/c++/v1"
      export LDFLAGS="-L ${LLVM_INSTALL}/lib -l c++ -l c++abi"
      export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${LLVM_INSTALL}/lib"
    fi
  - cd ${TRAVIS_BUILD_DIR}

script:
  - ./travis.sh

after_success:
  - if [[ -n "${COVERAGE}" ]]; then bash <(curl -s https://codecov.io/bash); fi
